
"use strict"
let menuArrows=document.querySelectorAll('.menu__arrow');if(menuArrows.length>0){for(let i=0;i<menuArrows.length;i++){const menuArrow=menuArrows[i];menuArrow.addEventListener('click',function(e){menuArrow.parentElement.classList.toggle('_active');});}}
var map=[];function init(){map=new ymaps.Map('map_2',{center:[0,0],zoom:16,});map.controls.remove('searchControl');map.controls.remove('trafficControl');map.controls.remove('geolocationControl');map.controls.remove('typeSelector');map.controls.remove('fullscreenControl');map.controls.remove('rulerControl');map.controls.remove(['scrollZoom']);map.behaviors.disable('scrollZoom');}
const burger=document.querySelector('.header__burger');if(burger){const menu=document.querySelector('.menu');burger.addEventListener('click',function(e){document.body.classList.toggle('_lock');burger.classList.toggle('_active');menu.classList.toggle('_active');});}
let lastScroll=0;const defaultOffset=50;const header=document.querySelector('.header');const scrollPosition=()=>window.pageYOffset||document.documentElement.scrollTop
const containHide=()=>header.classList.contains('_hide');window.addEventListener('scroll',()=>{if(scrollPosition()>lastScroll&&!containHide()&&scrollPosition()>defaultOffset){header.classList.add('_hide');}else if(scrollPosition()<lastScroll&&containHide()){header.classList.remove('_hide');}
if(lastScroll>50){header.classList.add('_paint');}else{header.classList.remove('_paint');}
lastScroll=scrollPosition();});const cardsParent=document.querySelector('.cards');const favourite=document.querySelector('.header__favourites');let favouriteItems={};let temporaryArray={};if(cardsParent){cardsParent.addEventListener('click',(e)=>{let targetElement=e.target;if(targetElement.closest('.cards__like')){const estateId=targetElement.closest('.real-estate-unit').dataset.id;let estate=targetElement.closest('.real-estate-unit').outerHTML;if(targetElement.classList.contains('cards__like--featured')){targetElement.classList.remove('cards__like--featured');delete favouriteItems[estateId];localStorage.setItem('favouriteItems',JSON.stringify(favouriteItems));}else{targetElement.classList.add('cards__like--featured');addToFavourites(targetElement,estateId);favouriteItems[estateId]=estate;localStorage.setItem('favouriteItems',JSON.stringify(favouriteItems));}
if(Object.keys(favouriteItems).length===0){localStorage.removeItem('favouriteItems');favourite.classList.remove('header__favourites--active');}}
if(targetElement.closest('.save-to-ls')){let estateId=targetElement.closest('.real-estate-unit').dataset.id;let estate=targetElement.closest('.real-estate-unit').outerHTML;temporaryArray={};temporaryArray[estateId]=estate;localStorage.setItem('temporaryArray',JSON.stringify(temporaryArray));}});}
if(localStorage.getItem('favouriteItems')){const likes=document.querySelectorAll('.cards__like');favourite.classList.add('header__favourites--active');favouriteItems=JSON.parse(localStorage.getItem('favouriteItems'));if(document.getElementById('featured-page')){let cardsList=document.querySelector('.cards__list');for(const key in favouriteItems){cardsList.innerHTML+=favouriteItems[key];}
cardsList.querySelectorAll('.cards__like').forEach(item=>{item.classList.add('cards__like--featured');})}
if(!document.querySelector('.flat')){for(let i=0;i<likes.length;i++){const like=likes[i];for(const key in favouriteItems){if(key==like.closest('.real-estate-unit').dataset.id){like.classList.add('cards__like--featured');}}}}}
const flatPage=document.querySelector('.flat');if(flatPage){if(Object.keys(favouriteItems).length===0){localStorage.removeItem('favouriteItems');favourite.classList.remove('header__favourites--active');}
temporaryArray=JSON.parse(localStorage.getItem('temporaryArray'));favouriteItems=JSON.parse(localStorage.getItem('favouriteItems'));if(localStorage.getItem('temporaryArray')){if(localStorage.getItem('favouriteItems')){for(const key in temporaryArray){if(key in favouriteItems){flatPage.querySelector('.flat__like').classList.add('flat__like--featured');}}}}
const flatLike=flatPage.querySelector('.flat__like');flatLike.onclick=()=>{if(localStorage.getItem('favouriteItems')){for(const key in temporaryArray){if(key in favouriteItems){delete favouriteItems[key];localStorage.setItem('favouriteItems',JSON.stringify(favouriteItems));flatLike.classList.remove('flat__like--featured');}else{favouriteItems[key]=temporaryArray[key];localStorage.setItem('favouriteItems',JSON.stringify(favouriteItems));flatLike.classList.add('flat__like--featured');}}}
if(!localStorage.getItem('favouriteItems')){favouriteItems={};for(const key in temporaryArray){favouriteItems[key]=temporaryArray[key];localStorage.setItem('favouriteItems',JSON.stringify(favouriteItems));flatLike.classList.add('flat__like--featured');favourite.classList.add('header__favourites--active');}}
if(Object.keys(favouriteItems).length===0){localStorage.removeItem('favouriteItems');favourite.classList.remove('header__favourites--active');}}}
function addToFavourites(likeButton,estateId){if(!likeButton.classList.contains('_hold')){likeButton.classList.add('_hold');likeButton.classList.add('_fly');const realEstateItem=document.querySelector(`[data-id="${estateId}"]`);const realEstateImage=realEstateItem.querySelector('.cards__image');const imageFly=realEstateImage.cloneNode(true);const imageFlyWidth=realEstateImage.offsetWidth;const imageFlyHeight=realEstateImage.offsetHeight;const imageFlyTop=realEstateImage.getBoundingClientRect().top;const imageFlyLeft=realEstateImage.getBoundingClientRect().left;imageFly.setAttribute('class','_flyImage');imageFly.style.cssText=`
			left: ${imageFlyLeft}px;
			top: ${imageFlyTop}px;
			width: ${imageFlyWidth}px;
			height: ${imageFlyHeight}px;
		`;document.body.append(imageFly);const cartFlyLeft=favourite.getBoundingClientRect().left;const cartFlyTop=favourite.getBoundingClientRect().top;imageFly.style.cssText=`
			left: ${cartFlyLeft}px;
			top: ${cartFlyTop}px;
			width: 0px;
			height: 0px;
			opacity: 0;
		`;imageFly.addEventListener('transitionend',function(){if(likeButton.classList.contains('_fly')){imageFly.remove();likeButton.classList.remove('_fly');likeButton.classList.remove('_hold');if(Object.keys(favouriteItems).length===0){favourite.classList.remove('header__favourites--active');}else{favourite.classList.add('header__favourites--active');}}});}}
const checkbuttons=document.querySelectorAll('.checkbutton');if(checkbuttons){for(let i=0;i<checkbuttons.length;i++){const checkbutton=checkbuttons[i];checkbutton.addEventListener('click',()=>{checkbutton.classList.toggle('checkbutton--active');});}}
document.querySelectorAll('.filter__trigger').forEach((trigger)=>{trigger.addEventListener('click',e=>{e.preventDefault();const id=e.target.getAttribute('href').replace('#','');document.querySelectorAll('.filter__trigger').forEach((child)=>child.classList.remove('filter__trigger--active'));document.querySelectorAll('.filter__tab').forEach((child)=>child.classList.remove('filter__tab--active'));trigger.classList.add('filter__trigger--active');document.getElementById(id).classList.add('filter__tab--active');document.querySelectorAll('.tab__trigger').forEach((child)=>child.classList.remove('tab__trigger--active'));document.querySelectorAll('.tab__item').forEach((child)=>child.classList.remove('tab__item--active'));document.getElementById(id).querySelector('.tab__trigger').classList.add('tab__trigger--active');document.getElementById(id).querySelector('.tab__item').classList.add('tab__item--active');});});if(document.querySelector('.filter__trigger')){document.querySelector('.filter__trigger').click();}
document.querySelectorAll('.tab__trigger').forEach((trigger)=>{trigger.addEventListener('click',e=>{e.preventDefault();const id=e.target.getAttribute('href').replace('#','');document.querySelectorAll('.tab__trigger').forEach((child)=>child.classList.remove('tab__trigger--active'));document.querySelectorAll('.tab__item').forEach((child)=>child.classList.remove('tab__item--active'));trigger.classList.add('tab__trigger--active');document.getElementById(id).classList.add('tab__item--active');});});if(document.querySelector('.tab__trigger')){document.querySelector('.tab__trigger').click();}
const flats=document.querySelectorAll('.tab__flat');if(flats){for(let i=0;i<flats.length;i++){const flat=flats[i];flat.addEventListener('click',()=>{flat.classList.toggle('tab__flat--active');});}}
if(document.querySelector('.slider')){new Swiper('.slider',{navigation:{nextEl:'.slider__button-next',prevEl:'.slider__button-prev'},keyboard:{enabled:true,onlyInViewport:true},slidesPerView:3,watchOverflow:true,spaceBetween:30,breakpoints:{320:{slidesPerView:1,spaceBetween:10,},360:{slidesPerView:1.5,},480:{slidesPerView:2,},992:{slidesPerView:2.5,spaceBetween:20,},1024:{slidesPerView:3,spaceBetween:30,}}});}
if(document.querySelector('.img-slider')){new Swiper('.img-slider',{navigation:{nextEl:'.img-slider__button-next',prevEl:'.img-slider__button-prev'},autoHeight:true,watchOverflow:true,observer:true,observeParents:true,observeSlideChildren:true,effect:'fade',fadeEffect:{crossFade:true},preloadImages:false,lazy:{loadOnTransitionStart:false,loadPrevNext:false,},watchSlidesProgress:true,watchSlidesVisibility:true,thumbs:{swiper:{el:'.img-slider-small',slidesPerView:4,watchOverflow:true,observer:true,observeParents:true,observeSlideChildren:true,direction:'vertical',spaceBetween:12,slideToClickedSlide:true,preloadImages:false,lazy:{loadOnTransitionStart:false,loadPrevNext:false,},watchSlidesProgress:true,watchSlidesVisibility:true,}},});}
document.querySelectorAll('.presentation__trigger').forEach((trigger)=>{trigger.addEventListener('click',e=>{e.preventDefault();const id=e.target.getAttribute('href').replace('#','');document.querySelectorAll('.presentation__trigger').forEach((child)=>child.classList.remove('presentation__trigger--active'));document.querySelectorAll('.presentation__tab').forEach((child)=>child.classList.remove('presentation__tab--active'));trigger.classList.add('presentation__trigger--active');document.getElementById(id).classList.add('presentation__tab--active');});});if(document.querySelector('.presentation__trigger')){document.querySelector('.presentation__trigger').click();}
const forms=document.querySelectorAll('.form');if(forms){for(let i=0;i<forms.length;i++){const form=forms[i];form.addEventListener('submit',(e)=>{const name=form.querySelector('.validation-name');const phone=form.querySelector('.validation-phone');const checkbox=form.querySelector('.validation-checkbox');const formAlert=form.querySelector('.validation-alert');const formLabel=form.querySelector('.validation-label');if(name.value==''||name.value==null){e.preventDefault();formAlert.classList.add('_error');name.classList.add('_error');}else{name.classList.remove('_error');}
if(phone.value==''||phone.value==null){e.preventDefault();formAlert.classList.add('_error');phone.classList.add('_error');}else{phone.classList.remove('_error');}
if(!checkbox.checked){e.preventDefault();formAlert.classList.add('_error');formLabel.classList.add('_error');}else{formLabel.classList.remove('_error');}});}}
const filter=document.getElementById('filter');if(filter){filter.addEventListener("click",(e)=>{let targetItem=e.target;if(targetItem.closest('.tab__advanced')){let tabInputs=document.querySelector('.tab__inputs');if(tabInputs.classList.contains('_spread')){tabInputs.classList.remove('_spread');targetItem.closest('.tab__advanced').innerText='Расширенный поиск';}else{tabInputs.classList.add('_spread');targetItem.closest('.tab__advanced').innerText='Свернуть фильтр';}}});}
$(document).ready(function(){ymaps.ready(init);})
const popupLinks=document.querySelectorAll('.popup-link');const body=document.querySelector('body');const menu=document.querySelector('.menu');const lockPadding=document.querySelectorAll('.lock-padding');const featuredBlock=document.querySelector('.featured');let unlock=true;const timeout=400;body.addEventListener("click",(e)=>{let targetItem=e.target;if(targetItem.closest('.popup-link')){const popupName=targetItem.getAttribute('href').replace('#','');const currentPopup=document.getElementById(popupName);popupOpen(currentPopup);e.preventDefault();if(targetItem.closest('.real-estate-unit')){let currentLatitude=targetItem.closest('.real-estate-unit').dataset.latitude;let currentLongitude=targetItem.closest('.real-estate-unit').dataset.longitude;let estateReady=targetItem.closest('.real-estate-unit').querySelector('.cards__ready').textContent;let estateCost=targetItem.closest('.real-estate-unit').querySelector('.cards__cost').textContent;let estatePrice=targetItem.closest('.real-estate-unit').querySelector('.cards__price').textContent;let estateFlat=targetItem.closest('.real-estate-unit').querySelector('.cards__flat').textContent;let estateFeatures=targetItem.closest('.real-estate-unit').querySelector('.cards__features').innerHTML;currentPopup.querySelector('.popup__flat').textContent=estateFlat;currentPopup.querySelector('.popup__ready').textContent=estateReady;currentPopup.querySelector('.popup__cost').textContent=estateCost;currentPopup.querySelector('.popup__price').textContent=estatePrice;currentPopup.querySelector('.popup__stats').innerHTML=estateFeatures;var myGeoObjects=new ymaps.GeoObjectCollection({},{preset:"islands#redCircleIcon",strokeWidth:4,geodesic:true});map.geoObjects.removeAll();myGeoObjects.add(new ymaps.Placemark([Number(currentLatitude),Number(currentLongitude)],{balloonContentHeader:`
					<a href="#" class="balloon-title">${estateFlat}</a>
					`,balloonContentFooter:`<div class="balloon-footer">${estatePrice}</div>`,},{iconLayout:'default#image',iconImageHref:'template/images/placemark.svg',iconImageSize:[70,70],iconImageOffset:[-35,-70]}));map.geoObjects.add(myGeoObjects);map.setCenter([Number(currentLatitude),Number(currentLongitude)]);}}});const popupCloseIcon=document.querySelectorAll('.close-popup');if(popupCloseIcon.length>0){for(let index=0;index<popupCloseIcon.length;index++){const el=popupCloseIcon[index];el.addEventListener('click',function(e){if(burger.classList.contains('_active')){burger.classList.remove('_active');menu.classList.remove('_active');body.classList.remove('_lock');}
popupClose(el.closest('.popup'));e.preventDefault();});}}
function popupOpen(currentPopup){if(currentPopup&&unlock){const popupActive=document.querySelector('.popup._open');if(popupActive){popupClose(popupActive,false);}else{bodyLock();}
currentPopup.classList.add('_open');currentPopup.addEventListener('click',function(e){if(!e.target.closest('.popup__content')){popupClose(e.target.closest('.popup'));}});}}
function popupClose(popupActive,doUnlock=true){if(unlock){popupActive.classList.remove('_open');if(doUnlock){bodyUnlock();}}}
function bodyLock(){const lockPaddingValue=window.innerWidth-document.querySelector('.wrapper').offsetWidth+'px';if(lockPadding.length>0){for(let index=0;index<lockPadding.length;index++){const el=lockPadding[index];el.style.paddingRight=lockPaddingValue;}}
body.style.paddingRight=lockPaddingValue;body.classList.add('_lock');unlock=false;setTimeout(function(){unlock=true;},timeout);}
function bodyUnlock(){setTimeout(function(){if(lockPadding.length>0){for(let index=0;index<lockPadding.length;index++){const el=lockPadding[index];el.style.paddingRight='0px';}}
body.style.paddingRight='0px';body.classList.remove('_lock');},timeout);unlock=false;setTimeout(function(){unlock=true;},timeout);}
document.addEventListener('keydown',function(e){if(e.which===27){const popupActive=document.querySelector('.popup._open');popupClose(popupActive);}});(function(){if(!Element.prototype.closest){Element.prototype.closest=function(css){var node=this;while(node){if(node.matches(css))return node;else node=node.parentElement;}
return null;};}})();(function(){if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector;}})();